AllCops:
  TargetRubyVersion: 2.4
Metrics/MethodLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Style/MethodMissingSuper:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
